---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: appbricks/automation-tools

inputs:
- name: spring-music-cicd
- name: version

run:
  path: spring-music-cicd/pipelines/cicd-k8s/deploy/task.sh

params:
  ENVIRONMENT:
  PKS_API_ENDPOINT:
  PKS_USERNAME:
  PKS_PASSWORD:
  DOCKER_REGISTRY_SERVER:
  DOCKER_REGISTRY_USERNAME:
  DOCKER_REGISTRY_PASSWORD:
