---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

inputs:
- name: spring-music-cicd
- name: version

run:
  path: spring-music-cicd/pipelines/cicd-k8s/deploy/task.sh

params:
  ENVIRONMENT:
